name: Bug
description: File a bug report
title: bug title
labels: enhancement
assignees: team-member
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Software Version
      description: "Which version of this software is being used"
      placeholder: "11.5.2"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser name and version
      description: "If applicable, Which browser and version of the browser is being used"
      placeholder: "chrome 22"
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can easily drag and drop screenshots here.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Addtional Context
      description: "Add any other context about the problem here."
