name: Feature Request
description: Suggest an idea for this project
title: Feature Request Title
labels: enhancement
assignees: team-member
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the behaviour in the existing issues.

        ---

        Thank you for taking the time to file a feature request. To address this feature request as fast as possible, we need some information.
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: logs
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Addtional Context
      description: "Add any other context or screenshots about the feature request here."
